const WATCHES={
"ROLEX|126610LN":{brand:"Rolex",reference:"126610LN",model:"Submariner Date",mapping:"DEMO VERIFIED",meta:["41 mm","Automatic","Oystersteel"],safety:{level:"safe",title:"No special opening restriction flagged",copy:"Normal bench opening procedure applies in this prototype."},facts:[["Movement","Cal. 3235","Useful internal cross-check"],["Case","41 mm Oystersteel","Reference-level case context"],["Bezel","Black ceramic","Useful visual configuration"],["Dial","Black","Expected configuration"]],warnings:[],serial:"Prototype serial intelligence is intentionally limited. Use serial dating only when a reliable brand-specific source supports it.",referenceIntel:"Prototype exact-reference record. Only information considered useful at the bench is surfaced.",provenance:"Prototype/test record only. Production data needs field-level sourcing and review."},
"TUDOR|25600T":{brand:"Tudor",reference:"25600T",model:"Pelagos",mapping:"SUPPORTED · REVIEW",meta:["42 mm","Automatic","Titanium"],safety:{level:"safe",title:"No special opening restriction flagged",copy:"Proceed normally. The app only shows the reference facts currently useful enough to surface."},facts:[["Movement","Cal. MT5612","Primary internal cross-check"],["Case","Titanium","Useful material check"],["Family","Pelagos","Reference family identified"]],warnings:[["Reference coverage is partial","Treat the shown information as useful guidance, not a complete specification sheet."]],serial:"Only show production-period guidance when supported; otherwise serial detail stays quiet.",referenceIntel:"Partial but useful mapping. Unknown fields are omitted rather than displayed.",provenance:"Prototype mapping. Production use requires verified sources."},
"BREITLING|A13340":{brand:"Breitling",reference:"A13340",model:"Chronomat / reference family",mapping:"FAMILY MATCH",meta:["Automatic chronograph","Family-level mapping"],safety:{level:"safe",title:"No special opening restriction flagged",copy:"Normal bench procedure applies; exact variant still needs visual/authenticator judgement."},facts:[["Movement","7750-derived Breitling calibre family","Useful architecture check"],["Family","Chronomat","Family-level identification"]],warnings:[["Family match only","Do not treat family-level data as an exact dial or case-variant specification."]],serial:"Serial dating should only appear when the database has reliable period-specific support.",referenceIntel:"This is intentionally family-level. The app avoids pretending an exact variant is known.",provenance:"Prototype family record only."},
"SINN|UX":{brand:"Sinn",reference:"UX",model:"UX / HYDRO family",mapping:"SAFETY DEMO",meta:["Quartz diver","HYDRO technology"],safety:{level:"stop",title:"DO NOT OPEN — special fluid-filled construction",copy:"Stop the normal opening workflow and follow verified manufacturer/specialist handling guidance."},facts:[["Construction","HYDRO fluid-filled system","Changes normal bench handling"],["Movement type","Quartz","Reference-family context"]],warnings:[["Special handling required","This is exactly the kind of information WatchAuthPro should interrupt the workflow for."]],serial:"No useful prototype serial guidance is surfaced.",referenceIntel:"Safety-first record. The important information is the handling warning, not a long technical dump.",provenance:"Prototype safety example only."}
};

const els={brand:document.getElementById("brandInput"),ref:document.getElementById("referenceInput"),serial:document.getElementById("serialInput"),load:document.getElementById("loadBtn"),reset:document.getElementById("resetBtn"),workspace:document.getElementById("workspace"),empty:document.getElementById("emptyState"),safety:document.getElementById("safetyGate"),brandLabel:document.getElementById("brandLabel"),modelLabel:document.getElementById("modelLabel"),identityMeta:document.getElementById("identityMeta"),mapping:document.getElementById("mappingConfidence"),coverage:document.getElementById("coverageBadge"),facts:document.getElementById("quickFacts"),noFacts:document.getElementById("noFacts"),warningsPanel:document.getElementById("warningsPanel"),warnings:document.getElementById("warningsList"),toggleIssue:document.getElementById("toggleIssueBtn"),issueBox:document.getElementById("issueBox"),issue:document.getElementById("issueInput"),finalNote:document.getElementById("finalNote"),copyNote:document.getElementById("copyNoteBtn"),copyStatus:document.getElementById("copyNoteStatus"),refIntel:document.getElementById("referenceIntel"),serialIntel:document.getElementById("serialIntel"),provenance:document.getElementById("provenance")};
let current=null;
function norm(v){return String(v||"").trim().toUpperCase()}
function unknownRecord(){return{brand:els.brand.value||"Unknown brand",reference:els.ref.value||"No reference",model:"Reference not mapped",mapping:"UNKNOWN",meta:[],safety:{level:"caution",title:"No opening guidance available",copy:"WatchAuthPro has no verified special-construction rule for this reference. Use normal professional judgement."},facts:[],warnings:[],serial:"No useful serial intelligence is loaded for this reference.",referenceIntel:"No exact mapping is present. The app intentionally shows nothing rather than filling the screen with unknown fields.",provenance:"No production evidence attached."}}
function loadWatch(){current=WATCHES[norm(els.brand.value)+"|"+norm(els.ref.value)]||unknownRecord();els.issue.value="";els.issueBox.classList.add("hidden");els.toggleIssue.textContent="Add issue";render()}
function render(){els.workspace.classList.remove("hidden");els.empty.classList.add("hidden");els.safety.className="safety-gate "+current.safety.level;els.safety.innerHTML='<div class="safety-title">'+(current.safety.level==="stop"?"⛔ ":current.safety.level==="caution"?"⚠ ":"✓ ")+current.safety.title+'</div><div class="safety-copy">'+current.safety.copy+'</div>';els.brandLabel.textContent=current.brand+" · "+current.reference;els.modelLabel.textContent=current.model;els.identityMeta.innerHTML=current.meta.map(x=>'<span>'+escapeHtml(x)+'</span>').join("");els.mapping.textContent=current.mapping;els.coverage.textContent=current.facts.length?current.facts.length+" useful facts loaded":"No useful facts loaded";els.facts.innerHTML=current.facts.map(f=>'<div class="fact-card"><span>'+escapeHtml(f[0])+'</span><strong>'+escapeHtml(f[1])+'</strong><p>'+escapeHtml(f[2])+'</p></div>').join("");els.noFacts.classList.toggle("hidden",!!current.facts.length);els.warningsPanel.classList.toggle("hidden",!current.warnings.length);els.warnings.innerHTML=current.warnings.map(w=>'<div class="warning-item"><strong>'+escapeHtml(w[0])+'</strong><p>'+escapeHtml(w[1])+'</p></div>').join("");els.refIntel.innerHTML='<dl><dt>Reference</dt><dd>'+escapeHtml(current.reference)+'</dd><dt>Mapping state</dt><dd>'+escapeHtml(current.mapping)+'</dd><dt>Detail</dt><dd>'+escapeHtml(current.referenceIntel)+'</dd></dl>';els.serialIntel.innerHTML='<dl><dt>Entered serial</dt><dd>'+escapeHtml(els.serial.value||"Not entered")+'</dd><dt>Guidance</dt><dd>'+escapeHtml(current.serial)+'</dd></dl>';els.provenance.innerHTML='<dl><dt>Evidence status</dt><dd>'+escapeHtml(current.provenance)+'</dd><dt>Prototype warning</dt><dd>Test data only — not suitable as an authentication authority.</dd></dl>';generateNote()}
function generateNote(){if(!current)return;const bits=[];bits.push([current.brand,current.model,current.reference?"Ref. "+current.reference:""].filter(Boolean).join(" — "));if(els.serial.value.trim())bits.push("Serial: "+els.serial.value.trim());if(current.safety.level==="stop")bits.push("Special construction identified; normal case-opening workflow not carried out.");if(els.issue.value.trim())bits.push("Issue noted: "+els.issue.value.trim()+".");else if(current.mapping==="UNKNOWN")bits.push("No useful reference-specific authentication data available in WatchAuthPro.");else bits.push("Available WatchAuthPro reference information reviewed; no discrepancy recorded.");els.finalNote.value=bits.join("\n");els.copyStatus.textContent=""}
async function copyNote(){const t=els.finalNote.value.trim();if(!t)return;try{await navigator.clipboard.writeText(t);els.copyStatus.textContent="Copied to clipboard."}catch(e){els.finalNote.focus();els.finalNote.select();const ok=document.execCommand("copy");els.copyStatus.textContent=ok?"Copied to clipboard.":"Select the note and copy it manually."}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
els.toggleIssue.addEventListener("click",()=>{const hidden=els.issueBox.classList.toggle("hidden");els.toggleIssue.textContent=hidden?"Add issue":"Hide issue";if(!hidden)els.issue.focus();generateNote()});
els.issue.addEventListener("input",generateNote);els.serial.addEventListener("input",()=>{if(current){els.serialIntel.innerHTML='<dl><dt>Entered serial</dt><dd>'+escapeHtml(els.serial.value||"Not entered")+'</dd><dt>Guidance</dt><dd>'+escapeHtml(current.serial)+'</dd></dl>';generateNote()}});
els.copyNote.addEventListener("click",copyNote);els.load.addEventListener("click",loadWatch);els.ref.addEventListener("keydown",e=>{if(e.key==="Enter")loadWatch()});els.reset.addEventListener("click",()=>{els.brand.value="";els.ref.value="";els.serial.value="";els.workspace.classList.add("hidden");els.empty.classList.remove("hidden");current=null});
document.querySelectorAll("[data-sample]").forEach(btn=>btn.addEventListener("click",()=>{const [brand,ref]=btn.dataset.sample.split("|");els.brand.value=brand;els.ref.value=ref;loadWatch()}));